title: "Prajwal Kammardi Arunachala"
email: "your.email@example.com"
description: >-
  Researcher in Microstructure-Informed Computational Mechanics
baseurl: ""
url: "https://yourgithubusername.github.io"
theme: minima
